### ISSUE TITLE
What should I do to create a study using the i2b2 data loaded?

### ISSUE THREAD

**Issue by lvcheng1031** [thehyve/transmart-batch#48]
Now, I am considering using Transmart as a hospital's Clinical Data Repository by importing all the clinical data into the transmart. 
By this transmart-batch project,I had imported the i2b2 format data successfully. But nothing happen to the concept navigation tree. What should I do to create a study using the i2b2 data loaded?

**Comment by cataphract** [comment]
There used to be a bug until a few months ago where entries in the `table_access` for the root nodes were not created. This has been fixed for a quite some time now though.

Make sure you're using the latest version. If the problem persists, please open an issue and follow the guidelines below.

---
Successful diagnosing and fixing bugs requires accurate, comprehensive and reproducible data. Make sure to include at least these elements:
Which version are you using? If you are using a git checkout, provide the hash of the checked out commit (you can use git rev-parse HEAD for this). If the project is composed of several repositories, include this information for all relevant repositories. If your project requires a build step, make sure that you run this build step after checking out a new version. If in doubt, clean and build project again.
If only the latest version/commit is supported, make sure you have updated to that version.
If you are interacting with a web application that you did not deploy, provide the time of that interaction instead.

* What did you do? Include the steps you took to arrive at your error condition. This information should be complete enough so that the person handling the bug can reproduce the problem. This means that, for instance, input files may need to be included as well. If this is a web application, provide also its URL.
* What did you get? Describe the result you obtained after executing the actions mentioned in the last point. Include all the relevant information you can. This can include full logs, error messages, screenshots, database state and so on.
* What did you expect? How do the results that you got differ from those that that you expected? If it's not immediately clear that the results you expect are the correct results, provide a explanation for why you think it is the case.
